# Generated by Django 5.0.2 on 2024-02-24 07:56

import world_of_speed.custom_validators.profile_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15, validators=[world_of_speed.custom_validators.profile_validators.custom_min_length_validator, world_of_speed.custom_validators.profile_validators.validate_user])),
                ('email', models.EmailField(max_length=254)),
                ('age', models.SmallIntegerField(validators=[world_of_speed.custom_validators.profile_validators.validate_age])),
                ('password', models.CharField(max_length=20)),
                ('first_name', models.CharField(blank=True, max_length=25, null=True)),
                ('last_name', models.CharField(blank=True, max_length=25, null=True)),
                ('profile_picture', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
